// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5IhTr0GcM_0mj8ncCOLDOL4POo_Vf1w',
    appId: '1:587072840255:web:85315a1c2605eb435b8e8a',
    messagingSenderId: '587072840255',
    projectId: 'spacenews-app',
    authDomain: 'spacenews-app.firebaseapp.com',
    databaseURL: 'https://spacenews-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacenews-app.appspot.com',
    measurementId: 'G-P6PSV2GB3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINhdR56L2k9crlGforzNtOpe4xPBzlto',
    appId: '1:587072840255:android:c65f660403becf2d5b8e8a',
    messagingSenderId: '587072840255',
    projectId: 'spacenews-app',
    databaseURL: 'https://spacenews-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacenews-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdzCnerRrgVcY4KcTct86v-uqavxv2VY',
    appId: '1:587072840255:ios:d37d8bae9ae5a85b5b8e8a',
    messagingSenderId: '587072840255',
    projectId: 'spacenews-app',
    databaseURL: 'https://spacenews-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacenews-app.appspot.com',
    iosBundleId: 'com.example.technicalDz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApdzCnerRrgVcY4KcTct86v-uqavxv2VY',
    appId: '1:587072840255:ios:23fc0579b53289c35b8e8a',
    messagingSenderId: '587072840255',
    projectId: 'spacenews-app',
    databaseURL: 'https://spacenews-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacenews-app.appspot.com',
    iosBundleId: 'com.example.technicalDz.RunnerTests',
  );
}
